[project]
name = "fly-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "brian2>=2.10.1",
    "cloud-volume>=12.14.4",
    "duckdb>=1.5.5",
    "duckdb-engine>=0.17.0",
    "fastapi>=0.141.1",
    "matplotlib>=3.11.1",
    "navis>=1.12.0",
    "networkx>=3.6.1",
    "neuprint-python>=0.6.3",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pypika>=0.51.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "scipy>=1.18.1",
    "sqlmodel>=0.0.42",
    "tqdm>=4.70.0",
    "trimesh>=5.1.0",
    "uvicorn>=0.52.4",
]
